services:
  - type: web
    name: poly-av-control-app
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: BASIC_USER
        value: AVControl
      - key: BASIC_PASS
        value: 123
